config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users'), name='users'),
    path('', include('main.urls', namespace='main'), name='main'),
    path('table-reservation/', include('table_rezerv.urls', namespace='table_rezerv'), name='table_rezerv'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from main.apps import MainConfig
from main.views import (
    IndexView, AboutView
)

app_name = MainConfig.name

urlpatterns = [
                  path('', IndexView.as_view(), name='index'),
                  path('about/', AboutView.as_view(), name='about'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

table_rezerv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from table_rezerv.apps import TableRezervConfig
from table_rezerv.views import (
    TableView, ReservationCreateView,
    ReservationConfirmView, ReservationCancelView,
    ReservationChangeView
)

app_name = TableRezervConfig.name

urlpatterns = [
                  path('', TableView.as_view(), name='index'),
                  path('reservation-create/<int:table_pk>', ReservationCreateView.as_view(), name='reservation_create'),
                  path('reservation-change/<int:pk>', ReservationChangeView.as_view(), name='reservation_change'),

                  path('reservation-confirm/<int:pk>', ReservationConfirmView.as_view(), name='reservation_confirm'),
                  path('reservation-cancel/<int:pk>', ReservationCancelView.as_view(), name='reservation_cancel'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    UserLoginView, UserRegisterView,
    UserProfileView, verify_mail, reset_password
)

app_name = UsersConfig.name

urlpatterns = [
                  path('login/', UserLoginView.as_view(), name='login'),
                  path('logout/', LogoutView.as_view(), name='logout'),
                  path('register/', UserRegisterView.as_view(), name='register'),

                  path('profile/<int:pk>', UserProfileView.as_view(), name='profile'),

                  path('verify/<str:token_auf>', verify_mail, name='verify'),
                  path('reset_password/', reset_password, name='reset_password'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Кастомный менеджер пользователя
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """
        Создает и возвращает пользователя с email и паролем.
        """
        if not email:
            raise ValueError('Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Создает и возвращает суперпользователя с email и паролем.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None

    name = models.CharField(verbose_name='Имя', max_length=30, **NULLABLE)
    email = models.EmailField(verbose_name='Почта', unique=True)
    phone = models.CharField(max_length=13, unique=True, verbose_name="Телефон")

    token_auf = models.CharField(max_length=255, **NULLABLE, verbose_name='Токен')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f"{self.name}"

    @property
    def detailed_info(self):
        return (f"Имя: {self.name}, Почта: {self.email}, Телефон:{self.phone}, "
                f"{'Активен' if self.is_active else 'Не активен'}")

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.password_validation import validate_password

from users.models import User


class CustomFormMixin:
    """Стилизация внешнего вида формы"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(CustomFormMixin, UserCreationForm):
    # Наследуемся от специальной формы UserCreationForm из модуля auth
    phone = forms.CharField(
        max_length=13,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'pattern': r'\d{10}',  # Валидация через HTML5 pattern (только 10 цифр)
            'title': 'Номер телефона без +7 и без 8',
            'required': 'required',
        }),
        label='Номер телефона'
    )

    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=None,  # Убирает стандартные подсказки
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text=None,
    )

    class Meta:
        model = User
        fields = ('name', 'phone', 'email', 'password1', 'password2')

    def clean_password1(self):
        password = self.cleaned_data.get('password1')
        validate_password(password, self.instance)
        return password

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают.")
        return password2

    # оставил старый вариант пусть будет))
    # class Meta:
    #     model = User
    #     # Указываем новую кастомную модель
    #     fields = ('name', 'phone', 'email', 'password1', 'password2')
    #     # Меняем поля, так как исходная форма UserCreationForm
    #     # ссылается на поле username


class UserLoginForm(CustomFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')

users/views.py
import random
import re
import secrets
import string

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView

from config.settings import EMAIL_HOST_USER
from table_rezerv.models import Reservation
from users.forms import UserLoginForm
from users.forms import UserRegisterForm
from users.models import User


class MyLoginRequiredMixin(LoginRequiredMixin):
    """Миксин для всех страниц, которые требуют авторизации"""
    login_url = 'users:login'
    redirect_field_name = "redirect_to"


class UserLoginView(LoginView):
    """Страничка входа"""
    template_name = 'users/login.html'
    form_class = UserLoginForm
    redirect_authenticated_user = True  # авторизовать пользователя при успешном входе

    def get_success_url(self):
        user_pk = self.request.user.pk
        return reverse('users:profile', kwargs={'pk': user_pk})


class UserRegisterView(CreateView):
    """Страничка регистрации нового пользователя"""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/registr.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Отправка пользователю письма с подтверждением регистрации"""
        phone = form.cleaned_data.get('phone')
        regular = re.sub(r'\D', '', phone)
        if len(regular) != 10:
            form.add_error('phone', 'Номер телефона должен содержать ровно 10 цифр.')
            return super().form_invalid(form)
        formatted_phone = f"+7{regular}"

        existing_user = User.objects.filter(phone=formatted_phone).first()
        if existing_user:
            form.add_error('phone', 'Этот номер телефона уже зарегистрирован.')
            return super().form_invalid(form)

        user = form.save(commit=False)
        user.phone = formatted_phone
        user.is_active = False
        token_auf = secrets.token_hex(16)  # генерит токен
        user.token_auf = token_auf
        user.save()
        host = self.request.get_host()  # это получение хоста
        url = f'http://{host}/users/verify/{token_auf}'
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Для подтверждения регистрации перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        # return super().form_valid(form)
        return render(self.request, 'users/register_successfully.html', {
            'email': user.email
        })


def verify_mail(request, token_auf):
    """Подтверждение регистрации переход по ссылке из письма и редирект на страницу входа"""
    user = get_object_or_404(User, token_auf=token_auf)  # получить пользователя токен
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def reset_password(request):
    """Сброс пароля и отправка письма """

    if request.method == 'POST':
        email = request.POST.get('email')

        if not User.objects.filter(email=email).exists():
            # это чтобы яндекс не пытался отправить письмо на не существующий адрес
            return render(request, template_name='users/reset_password.html')
        else:
            user = get_object_or_404(User, email=email)
            new_password = ''.join(random.choices(string.ascii_letters + string.digits, k=8))  # генерит новый пароль
            user.set_password(new_password)
            user.save()
            send_mail(
                subject=f'Сброс пароля',
                message=f'Ваш новый пароль: {new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
            )
        return redirect(reverse('users:login'))

    return render(request, template_name='users/reset_password.html')


class UserProfileView(MyLoginRequiredMixin, DetailView):
    """Страничка просмотра профиля пользователя"""
    model = User
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reservations'] = Reservation.objects.filter(customer=self.request.user).order_by('-date', '-time')
        return context

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 col-lg-4">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-flex justify-content-center mt-3">
                            <button type="submit" class="btn btn-outline-primary w-110">Войти</button>
                        </div>
                    </form>
                    <div class="mt-4 text-center">
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:reset_password' %}">Забыли
                            пароль?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <!-- Поля профиля пользователя -->
                <h2>Профиль</h2>
                <p><strong>Имя:</strong> {{ user.name }}</p>
                {% if user == request.user %}
                    <p><strong>Номер телефона:</strong> {{ user.phone }}</p>
                    <p><strong>Email:</strong> {{ user.email }}</p>
                {% endif %}
            </div>
            <div class="card-body">
            
                {% for rez in reservations %}
                    <p class="lead">{{ rez }}
                        {% if rez.status == 'pending' %}
                            <span class="badge bg-primary">Ожидает подтверждения</span>
                        {% elif rez.status == 'confirmed' %}
                            <span class="badge bg-success">Подтверждена</span>
                        {% elif rez.status == 'cancelled' %}
                            <span class="badge bg-danger">Отменена</span>
                        {% elif rez.status == 'completed' %}
                            <span class="badge bg-danger">Завершена</span>
                        {% endif %}

                        {% if rez.status == 'pending' %}
                            <a href="{% url 'table_rezerv:reservation_confirm' rez.pk %}" style="color:white">
                                <span class="badge bg-success m-2">Подтвердить</span>
                            </a>
                            <a href="{% url 'table_rezerv:reservation_change' rez.pk %}" style="color:white">
                                <span class="badge bg-success m-2">Изменить</span>
                            </a>
                        {% endif %}

                        {% if rez.status == 'pending' or rez.status == 'confirmed' %}
                            <a href="{% url 'table_rezerv:reservation_cancel' rez.pk %}" style="color:white">
                                <span class="badge bg-danger m-2">Отменить</span>
                            </a>
                        {% endif %}
                    </p>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/users/register_successfully.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6 text-center">
                <div class="alert alert-info p-4">
                    <h4 class="alert-heading">Проверьте вашу почту!</h4>
                    <p class="mt-3" style="font-size: 1.2rem;">
                        На указанную почту <strong>{{ email }}</strong> было отправлено письмо со ссылкой 
                        для подтверждения регистрации.
                        Пожалуйста, проверьте вашу почту. 
                    </p>
                    <p class="text-muted mt-2">
                        Сообщение может оказаться в папке "Спам".
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/registr.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 col-lg-4">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-flex justify-content-center mt-3">
                            <button type="submit" class="btn btn-outline-primary w-110">Регистрация</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/reset_password.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 col-lg-4">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label">Почта:</label>
                    <input type="email" class="form-control" id="email"
                           name="email" required autocomplete="email">
                    <h6 class="mt-2">На указанную почту будет отправлено письмо с новым паролем</h6>
                </div>
                <div class="d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-outline-primary w-110">Сбросить</button>
                </div>
            </form>
        </div>
    </div>
</div>
    
{% endblock %}

templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}


        <div class="col-4 m-auto">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-primary">Сохранить</button>
            </form>
        </div>

{% endblock %}